import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Footer from "./component/Footer";
import Navbar from "./component/Navbar";
import { ToastContainer } from "react-toastify";
import Marquee from "./component/Marquee";




const notoSerifBengali = Noto_Serif_Bengali({
 
  subsets: ["latin","bengali"],
});

export const metadata: Metadata = {
  title: "Bazar Dor",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }: LayoutProps<"/">) {


  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
       <Navbar/>
       <Marquee/>
        <main>
          {children} 
        </main>
         <ToastContainer />
<Footer/>
        </body>
    </html>
  );
}
